name: Release
on:
  push:
    branches:
      - master
jobs:
  semantic-release:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install node modules
        run: |-
          npm install -g semantic-release \
            @semantic-release/exec \
            @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
